--drop table ilosci;
--drop table oferty;
--drop table produkty;
--drop table uczestnicy;
--drop sequence bd2a05.ucz;


-- Generated by Oracle SQL Developer Data Modeler 18.3.0.268.1156
--   at:        2019-01-18 21:51:41 CET
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g

CREATE user bd2a05_app identified by account unlock 
;

CREATE TABLE ilosci (
    ilosc                  NUMBER(6, 4),
    oferty_id              NUMBER(9) NOT NULL,
    produkt_kod_produktu   NUMBER(9) NOT NULL
)
LOGGING;

COMMENT ON COLUMN ilosci.ilosc IS
    'ilosc danego produktu w ustalonej ofercie';

COMMENT ON COLUMN ilosci.oferty_id IS
    'PF key(primary-foreign key)(to oferta)';

COMMENT ON COLUMN ilosci.produkt_kod_produktu IS
    'PF key(primary-foreign key)(to produkt)';

CREATE INDEX il_of_fk__idx ON
    ilosci (
        oferty_id
    DESC )
        LOGGING;

CREATE INDEX il_pr_fk__idx ON
    ilosci (
        produkt_kod_produktu
    ASC )
        LOGGING;

GRANT INSERT, SELECT, UPDATE, DELETE ON ilosci TO bd2a05_app WITH GRANT OPTION;

ALTER TABLE ilosci ADD CONSTRAINT il_pk PRIMARY KEY ( produkt_kod_produktu,
                                                      oferty_id );

CREATE TABLE oferty (
    id_oferty                  NUMBER(9) NOT NULL,
    wolumen                    NUMBER(5, 1),
    cena_wywolawcza            NUMBER(9, 2),
    okres_obowiazywania       DATE,
    uczestnicy_id_uczestnika   NUMBER(5) NOT NULL
)
LOGGING;

COMMENT ON COLUMN oferty.id_oferty IS
    'PK(primary key)';

COMMENT ON COLUMN oferty.wolumen IS
    'ilosc jednostek wiazki
';

COMMENT ON COLUMN oferty.cena_wywolawcza IS
    'cena jednostki wiazki';

COMMENT ON COLUMN oferty.okres_obowiazywania IS
    'data waznosci';

CREATE INDEX of_ucz_fk__idx ON
    oferty (
        uczestnicy_id_uczestnika
    ASC )
        LOGGING;

GRANT DELETE, SELECT, UPDATE, INSERT ON oferty TO bd2a05_app WITH GRANT OPTION;

ALTER TABLE oferty ADD CONSTRAINT of_pk PRIMARY KEY ( id_oferty );

CREATE TABLE produkty (
    kod_produktu   NUMBER(9) NOT NULL,
    name           VARCHAR2(15)
)
LOGGING;

COMMENT ON COLUMN produkty.kod_produktu IS
    'PK';

COMMENT ON COLUMN produkty.name IS
    'nazwa produktu';

GRANT INSERT, SELECT, UPDATE, DELETE ON produkty TO bd2a05_app WITH GRANT OPTION;

ALTER TABLE produkty ADD CONSTRAINT pr_pk PRIMARY KEY ( kod_produktu );

ALTER TABLE produkty ADD CONSTRAINT pr_name_un UNIQUE ( name );

CREATE TABLE uczestnicy (
    id_uczestnika   NUMBER(5) NOT NULL,
    name            VARCHAR2(30),
    surname         VARCHAR2(30)
)
LOGGING;

COMMENT ON COLUMN uczestnicy.id_uczestnika IS
    '(PK-primary key) Dla kazdego uczestnika';

GRANT DELETE, INSERT, SELECT, UPDATE ON uczestnicy TO bd2a05_app WITH GRANT OPTION;

ALTER TABLE uczestnicy ADD CONSTRAINT ucz_pk PRIMARY KEY ( id_uczestnika );

ALTER TABLE uczestnicy ADD CONSTRAINT ucz_surname_un UNIQUE ( surname );

ALTER TABLE ilosci
    ADD CONSTRAINT il_of_fk FOREIGN KEY ( oferty_id )
        REFERENCES oferty ( id_oferty )
    DEFERRABLE;

ALTER TABLE ilosci
    ADD CONSTRAINT il_pr_fk FOREIGN KEY ( produkt_kod_produktu )
        REFERENCES produkty ( kod_produktu )
    DEFERRABLE;

ALTER TABLE oferty
    ADD CONSTRAINT of_ucz_fk FOREIGN KEY ( uczestnicy_id_uczestnika )
        REFERENCES uczestnicy ( id_uczestnika )
    DEFERRABLE;



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                             4
-- CREATE INDEX                             3
-- ALTER TABLE                             12
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              1
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0


commit;